### ISSUE TITLE
SignedSDJWT properties and functions access

### ISSUE THREAD

**Issue by kuldar-daniel** [eu-digital-identity-wallet/eudi-lib-sdjwt-swift#17]
While the SignedSDJWT struct itself is public, it doesn't expose most of it's methods and variables as such, hence rendering them inaccessible for consumers of the library. I'm not exactly sure what should be public and what actually makes sense to keep internal, but I'd be happy to make a PR once someone can point it out to me.

Currently I am looking to re create the claims, but `recreateClaims()` functions is not public.

The same applies for many of the other properties and functions across the library - internal access does not make them callable by the library integrator.

**Comment by dtsiflit** [comment]
Hi @kuldar-daniel thank you for your comments. Please make a PR that suits your use case.
