### ISSUE TITLE
More a Request: Using a more complete Jose library as a dependency.

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [eu-digital-identity-wallet/eudi-lib-sdjwt-swift#22]
Hi guys.

First pretty awesome work you guys did here, we are thinking in adding this credential type to our Identus, and found this repo.

Given that you forked the Jose library, to add functionality.
I was wondering if you would consider switching to a different Jose library?

https://github.com/beatt83/jose-swift

It supports the encryption you guys require and much more (including EdDSA), it's more complete.
As we are using this library with success in Identus for JWS, JWE and JWT.

And given there are quite a few forks of the library your using so it adds other type of capabilities, it may become a dependency issue trying to use the awesome frameworks your working on with others, since they might target different forks of the same library.

I understand this could be a complex change since you would have to change on the other repos. But in the end it would be profitable.

**Comment by dtsiflit** [comment]
Hello @goncalo-frade-iohk , thank you for sharing this JOSE implementation!
We will have a look at it. At a quick glance it does indeed support our use cases.

**Comment by goncalo-frade-iohk** [comment]
Hey @dtsiflit. Thanks for the response. :) 

I made the changes on sd-jwt to use the other library. I think the refactoring could go further since this Jose library already supports JWTs, Nested JWTs and Claims DSL.

But if your interested with this changes all tests pass and additionally new cryptographic suits are supported mainly `EdDSA`.

;)

**Comment by goncalo-frade-iohk** [comment]
Forgot to add  the link: https://github.com/goncalo-frade-iohk/eudi-lib-sdjwt-swift

**Comment by dtsiflit** [comment]
> Forgot to add the link: https://github.com/goncalo-frade-iohk/eudi-lib-sdjwt-swift

That's great work @goncalo-frade-iohk , thank you very much.
If you would like to, you could open a PR on this repo also (or re-open your previous PR) 🙂

**Comment by goncalo-frade-iohk** [comment]
Will do so @dtsiflit I will just clean a bit this changes that I made before creating the PR. 👍

I got a question, the readme says this code base is for draft 5. But I was testing against draft 8 and it seems it already follows draft 8.

What is missing maybe I can provide some assistance in updating as well.

**Comment by goncalo-frade-iohk** [comment]
@dtsiflit done ;) https://github.com/eu-digital-identity-wallet/eudi-lib-sdjwt-swift/pull/24

**Comment by dtsiflit** [comment]
Thank you @goncalo-frade-iohk we'll try to get it merge in next week!
