### ISSUE TITLE
Question on the draft version

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [eu-digital-identity-wallet/eudi-lib-sdjwt-swift#26]
Hey @dtsiflit! I was testing the library and it seems it follows the draft 8 implementation already. Is there anything that is missing? :)

**Comment by dtsiflit** [comment]
Het @goncalo-frade-iohk! I'll be updating the readme to mention draft 8.

**Comment by dtsiflit** [comment]
Also added a link to jose-swift in the README @goncalo-frade-iohk

**Comment by goncalo-frade-iohk** [comment]
Awesome thanks :)
